[2024-06-02T14:48:11.114+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Collect_Prices.end_of_week_sensor scheduled__2024-06-02T14:44:00+00:00 [queued]>
[2024-06-02T14:48:11.132+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Collect_Prices.end_of_week_sensor scheduled__2024-06-02T14:44:00+00:00 [queued]>
[2024-06-02T14:48:11.134+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2024-06-02T14:48:11.175+0000] {taskinstance.py:2191} INFO - Executing <Task(TimeSensor): end_of_week_sensor> on 2024-06-02 14:44:00+00:00
[2024-06-02T14:48:11.195+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Collect_Prices', 'end_of_week_sensor', 'scheduled__2024-06-02T14:44:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/BTC_prediction.py', '--cfg-path', '/tmp/tmpo1uxsqp9']
[2024-06-02T14:48:11.190+0000] {standard_task_runner.py:60} INFO - Started process 4453 to run task
[2024-06-02T14:48:11.204+0000] {standard_task_runner.py:88} INFO - Job 123: Subtask end_of_week_sensor
[2024-06-02T14:48:11.242+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-02T14:48:11.363+0000] {task_command.py:423} INFO - Running <TaskInstance: Collect_Prices.end_of_week_sensor scheduled__2024-06-02T14:44:00+00:00 [running]> on host d886641e466e
[2024-06-02T14:48:11.509+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Collect_Prices' AIRFLOW_CTX_TASK_ID='end_of_week_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T14:44:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-02T14:44:00+00:00'
[2024-06-02T14:48:11.513+0000] {time_sensor.py:48} INFO - Checking if the time (2024-06-02 23:59:00) has come
[2024-06-02T14:48:11.516+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/time_sensor.py", line 49, in poke
    return timezone.make_naive(timezone.utcnow(), self.dag.timezone).time() > self.target_time
TypeError: '>' not supported between instances of 'datetime.time' and 'datetime.datetime'
[2024-06-02T14:48:11.530+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Collect_Prices, task_id=end_of_week_sensor, execution_date=20240602T144400, start_date=20240602T144811, end_date=20240602T144811
[2024-06-02T14:48:11.548+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 123 for task end_of_week_sensor ('>' not supported between instances of 'datetime.time' and 'datetime.datetime'; 4453)
[2024-06-02T14:48:11.584+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-02T14:48:11.626+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
