[2024-06-02T13:55:32.740+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Collect_Prices.weekly_run_model manual__2024-06-02T13:55:16.659091+00:00 [queued]>
[2024-06-02T13:55:32.749+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Collect_Prices.weekly_run_model manual__2024-06-02T13:55:16.659091+00:00 [queued]>
[2024-06-02T13:55:32.750+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-06-02T13:55:32.772+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): weekly_run_model> on 2024-06-02 13:55:16.659091+00:00
[2024-06-02T13:55:32.783+0000] {standard_task_runner.py:60} INFO - Started process 2477 to run task
[2024-06-02T13:55:32.787+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Collect_Prices', 'weekly_run_model', 'manual__2024-06-02T13:55:16.659091+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/BTC_prediction.py', '--cfg-path', '/tmp/tmph78wtvyt']
[2024-06-02T13:55:32.789+0000] {standard_task_runner.py:88} INFO - Job 82: Subtask weekly_run_model
[2024-06-02T13:55:32.810+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-02T13:55:32.853+0000] {task_command.py:423} INFO - Running <TaskInstance: Collect_Prices.weekly_run_model manual__2024-06-02T13:55:16.659091+00:00 [running]> on host d886641e466e
[2024-06-02T13:55:32.971+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Collect_Prices' AIRFLOW_CTX_TASK_ID='weekly_run_model' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T13:55:16.659091+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-02T13:55:16.659091+00:00'
[2024-06-02T13:55:35.401+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/BTC_prediction.py", line 74, in run_prediction_model
    print("Error in running the model", response.json())
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-06-02T13:55:35.421+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Collect_Prices, task_id=weekly_run_model, execution_date=20240602T135516, start_date=20240602T135532, end_date=20240602T135535
[2024-06-02T13:55:35.446+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 82 for task weekly_run_model (Expecting value: line 1 column 1 (char 0); 2477)
[2024-06-02T13:55:35.491+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-02T13:55:35.515+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
