[2024-06-02T14:44:31.195+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Collect_Prices.end_of_week_sensor scheduled__2024-06-02T14:42:00+00:00 [queued]>
[2024-06-02T14:44:31.214+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Collect_Prices.end_of_week_sensor scheduled__2024-06-02T14:42:00+00:00 [queued]>
[2024-06-02T14:44:31.216+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-06-02T14:44:31.242+0000] {taskinstance.py:2191} INFO - Executing <Task(TimeSensor): end_of_week_sensor> on 2024-06-02 14:42:00+00:00
[2024-06-02T14:44:31.253+0000] {standard_task_runner.py:60} INFO - Started process 4261 to run task
[2024-06-02T14:44:31.259+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Collect_Prices', 'end_of_week_sensor', 'scheduled__2024-06-02T14:42:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/BTC_prediction.py', '--cfg-path', '/tmp/tmpp63w0ca2']
[2024-06-02T14:44:31.261+0000] {standard_task_runner.py:88} INFO - Job 106: Subtask end_of_week_sensor
[2024-06-02T14:44:31.286+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-02T14:44:31.393+0000] {task_command.py:423} INFO - Running <TaskInstance: Collect_Prices.end_of_week_sensor scheduled__2024-06-02T14:42:00+00:00 [running]> on host d886641e466e
[2024-06-02T14:44:31.586+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Collect_Prices' AIRFLOW_CTX_TASK_ID='end_of_week_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T14:42:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-02T14:42:00+00:00'
[2024-06-02T14:44:31.591+0000] {time_sensor.py:48} INFO - Checking if the time (2024-06-02 23:59:00) has come
[2024-06-02T14:44:31.594+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/time_sensor.py", line 49, in poke
    return timezone.make_naive(timezone.utcnow(), self.dag.timezone).time() > self.target_time
TypeError: '>' not supported between instances of 'datetime.time' and 'datetime.datetime'
[2024-06-02T14:44:31.608+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=Collect_Prices, task_id=end_of_week_sensor, execution_date=20240602T144200, start_date=20240602T144431, end_date=20240602T144431
[2024-06-02T14:44:31.636+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 106 for task end_of_week_sensor ('>' not supported between instances of 'datetime.time' and 'datetime.datetime'; 4261)
[2024-06-02T14:44:31.673+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-02T14:44:31.734+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
