[2024-06-02T14:47:00.584+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Collect_Prices.end_of_day_sensor manual__2024-06-02T14:44:51.159741+00:00 [queued]>
[2024-06-02T14:47:00.597+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Collect_Prices.end_of_day_sensor manual__2024-06-02T14:44:51.159741+00:00 [queued]>
[2024-06-02T14:47:00.597+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2024-06-02T14:47:00.620+0000] {taskinstance.py:2191} INFO - Executing <Task(TimeSensor): end_of_day_sensor> on 2024-06-02 14:44:51.159741+00:00
[2024-06-02T14:47:00.629+0000] {standard_task_runner.py:60} INFO - Started process 4393 to run task
[2024-06-02T14:47:00.635+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Collect_Prices', 'end_of_day_sensor', 'manual__2024-06-02T14:44:51.159741+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/BTC_prediction.py', '--cfg-path', '/tmp/tmppc7w15j8']
[2024-06-02T14:47:00.638+0000] {standard_task_runner.py:88} INFO - Job 117: Subtask end_of_day_sensor
[2024-06-02T14:47:00.665+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-02T14:47:00.740+0000] {task_command.py:423} INFO - Running <TaskInstance: Collect_Prices.end_of_day_sensor manual__2024-06-02T14:44:51.159741+00:00 [running]> on host d886641e466e
[2024-06-02T14:47:00.883+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Collect_Prices' AIRFLOW_CTX_TASK_ID='end_of_day_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T14:44:51.159741+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-02T14:44:51.159741+00:00'
[2024-06-02T14:47:00.886+0000] {time_sensor.py:48} INFO - Checking if the time (2024-06-01 00:02:00) has come
[2024-06-02T14:47:00.889+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/time_sensor.py", line 49, in poke
    return timezone.make_naive(timezone.utcnow(), self.dag.timezone).time() > self.target_time
TypeError: '>' not supported between instances of 'datetime.time' and 'datetime.datetime'
[2024-06-02T14:47:00.901+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Collect_Prices, task_id=end_of_day_sensor, execution_date=20240602T144451, start_date=20240602T144700, end_date=20240602T144700
[2024-06-02T14:47:00.922+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 117 for task end_of_day_sensor ('>' not supported between instances of 'datetime.time' and 'datetime.datetime'; 4393)
[2024-06-02T14:47:00.953+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-02T14:47:00.997+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
