[2024-06-02T21:03:48.270+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Run_Module.weekly_run_model manual__2024-06-02T21:01:37.545205+00:00 [queued]>
[2024-06-02T21:03:48.283+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Run_Module.weekly_run_model manual__2024-06-02T21:01:37.545205+00:00 [queued]>
[2024-06-02T21:03:48.284+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2024-06-02T21:03:48.306+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): weekly_run_model> on 2024-06-02 21:01:37.545205+00:00
[2024-06-02T21:03:48.326+0000] {standard_task_runner.py:60} INFO - Started process 7824 to run task
[2024-06-02T21:03:48.334+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Run_Module', 'weekly_run_model', 'manual__2024-06-02T21:01:37.545205+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/BTC_prediction.py', '--cfg-path', '/tmp/tmpz0hmjbaz']
[2024-06-02T21:03:48.337+0000] {standard_task_runner.py:88} INFO - Job 132: Subtask weekly_run_model
[2024-06-02T21:03:48.360+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-06-02T21:03:48.414+0000] {task_command.py:423} INFO - Running <TaskInstance: Run_Module.weekly_run_model manual__2024-06-02T21:01:37.545205+00:00 [running]> on host d886641e466e
[2024-06-02T21:03:48.531+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Run_Module' AIRFLOW_CTX_TASK_ID='weekly_run_model' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T21:01:37.545205+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-02T21:01:37.545205+00:00'
[2024-06-02T21:03:48.548+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/BTC_prediction.py", line 59, in run_prediction_model
    raise ValueError("Token not found in XCom")
ValueError: Token not found in XCom
[2024-06-02T21:03:48.568+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Run_Module, task_id=weekly_run_model, execution_date=20240602T210137, start_date=20240602T210348, end_date=20240602T210348
[2024-06-02T21:03:48.590+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 132 for task weekly_run_model (Token not found in XCom; 7824)
[2024-06-02T21:03:48.624+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-02T21:03:48.657+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
